### PR TITLE
Raised Buttons

### PR DESCRIPTION
**Pull request by John-Lin**
Raised Buttons :rocket: 

screen shot 2015-12-02 at 2 33 13 pm

### CODE REVIEW

**Comment by inputsh** [comment]
I think that this PR kind of broke things for me.

screenshot from 2015-12-02 11 39 56

**Comment by lockys** [comment]
@aleksandar-todorovic 
Do you mean that the button move to the left side?
if yes, that's feature :cry: , it will hide when cursor do not hover it. and it also shows that the hiding feature may confuse the users.
if not, could you please provide more informations?

**Comment by John-Lin** [comment]
@aleksandar-todorovic Could you give more detail about that? and also provide your browser information.

**Comment by inputsh** [comment]
Oh, I haven't realized that the buttons are gliding in and out. But still, trying to do the same from a bigger monitor resulted in this:

screenshot from 2015-12-02 11 57 43

Seems a bit unnecessary to hide the buttons when there's plenty of space between the content and buttons. Tried both on Firefox (version 43.0b7) and Chrome (version 46.0.2490.86) and got the same result. In the third browser I have installed ([Midori](http://midori-browser.org/)), the issue is not present:

screenshot from 2015-12-02 12 01 23

I'm running each of them on Ubuntu 14.04.

My suggestion is to check the resolution first. If the resolution is small enough (lets say, 1366x768 or lower) then the icons should be hidden and gliding in as the user hovers over them. If the resolution is bigger (>1366x768), there's no need to hide the buttons since there's plenty of empty space on both sides of the screen.

**Comment by lockys** [comment]
You screen is so big. :sunglasses: 
We both are on 13" screen when development.

Thanks for your suggestions.
You point out that the importance of RWD. It's an issue about user experience.
We are going to re-think about how to satisfy users on different devices or screen.
There are still many improvements that needed to be done of this project.

**Pull request merged**
